# Exercícios de Pandas

## 1 Ler e visualizar dados

In [14]:
#Ler e visualizar os dados
import pandas as pd

tabela_dataframe = pd.read_excel("dados.xlsx")
display(tabela_dataframe)

   ID      Nome Departamento  Salario  Idade Data_Admissao
0   1       Ana   Financeiro     4200     28    2020-03-10
1   2     Bruno      Compras     3800     31    2019-07-22
2   3     Carla   Financeiro     4500     26    2021-11-01
3   4     Diego   Engenharia     6000     35    2018-02-15
4   5     Elisa      Compras     3700     29    2020-12-20
5   6    Felipe   Engenharia     6100     40    2017-08-12
6   7  Gabriela   Financeiro     4700     30    2022-05-09
7   8      Hugo   Engenharia     5800     33    2019-10-02
8   9      Iara      Compras     3900     25    2021-06-25
9  10      João   Financeiro     4300     27    2020-09-18

In [32]:
# Exibir as 5 primeiras linhas
display(tabela_dataframe.head(5))

#Exibir o total de linhas e colunas usando o método Len para medir o "comprimento da lista"
total_linhas = len(tabela_dataframe.index) #-> Usando Index
total_colunas = len(tabela_dataframe.columns)

display(total_linhas, total_colunas)


#Exibir

   ID   Nome Departamento  Salario  Idade Data_Admissao
0   1    Ana   Financeiro     4200     28    2020-03-10
1   2  Bruno      Compras     3800     31    2019-07-22
2   3  Carla   Financeiro     4500     26    2021-11-01
3   4  Diego   Engenharia     6000     35    2018-02-15
4   5  Elisa      Compras     3700     29    2020-12-20

10

6

In [34]:
#Exibir o total de linhas e colunas usando o método shape
print(tabela_dataframe.shape)

(10, 6)

## 2 Explorar o DataFrame

In [53]:
# 2.1 Liste todos os nomes das colunas
#Usar os column.values para exibir os valores dos dados das colunas
nomes_colunas = tabela_dataframe.columns.values 
print(nomes_colunas)

#Usar o método columns.tolist()
nomes_colunas = tabela_dataframe.columns.to_list()
print(nomes_colunas)

['ID' 'Nome' 'Departamento' 'Salario' 'Idade' 'Data_Admissao']
['ID', 'Nome', 'Departamento', 'Salario', 'Idade', 'Data_Admissao']

In [ ]:
# 2.2 Exiba as informações gerais (tipos de dados, nulos, etc.)
# Para isso, usar o método info.()
informacoes = tabela_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             10 non-null     int64
 1   Nome           10 non-null     object
 2   Departamento   10 non-null     object
 3   Salario        10 non-null     int64
 4   Idade          10 non-null     int64
 5   Data_Admissao  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 612.0+ bytes

In [84]:
# 2.3 Calcule a média de salários
media_salarios = tabela_dataframe["Salario"].mean()
print(media_salarios)

4700.0

## 3 Filtragem de dados

In [83]:
# 3.1 Mostre apenas os funcionários do departamento "Financeiro"
# Tabela, onde tabela[coluna] == "Parâmetro"
funcionarios_financeiro = tabela_dataframe[tabela_dataframe["Departamento"] == "Financeiro"]
display(funcionarios_financeiro)

# 3.2 Mostre quem ganha mais de R$4500
funcionarios_salarios = tabela_dataframe[tabela_dataframe["Salario"] > 4500]
display(funcionarios_salarios)


# 3.3 Mostre os funcionários com menos de 30 anos
funcionarios_anos = tabela_dataframe[tabela_dataframe["Idade"] < 30]
display(funcionarios_anos)

   ID      Nome Departamento  Salario  Idade Data_Admissao
0   1       Ana   Financeiro     4200     28    2020-03-10
2   3     Carla   Financeiro     4500     26    2021-11-01
6   7  Gabriela   Financeiro     4700     30    2022-05-09
9  10      João   Financeiro     4300     27    2020-09-18

   ID      Nome Departamento  Salario  Idade Data_Admissao
3   4     Diego   Engenharia     6000     35    2018-02-15
5   6    Felipe   Engenharia     6100     40    2017-08-12
6   7  Gabriela   Financeiro     4700     30    2022-05-09
7   8      Hugo   Engenharia     5800     33    2019-10-02

   ID   Nome Departamento  Salario  Idade Data_Admissao
0   1    Ana   Financeiro     4200     28    2020-03-10
2   3  Carla   Financeiro     4500     26    2021-11-01
4   5  Elisa      Compras     3700     29    2020-12-20
8   9   Iara      Compras     3900     25    2021-06-25
9  10   João   Financeiro     4300     27    2020-09-18

## 4 Ordenação de itens

In [99]:
# 4.1 Ordene o DataFrame por salário (decrescente)
tabela_ordenada = tabela_dataframe.sort_values("Salario", ascending=False)
display(tabela_ordenada)

# 4.2 Ordene por idade (crescente)
tabela_ordenada_idades = tabela_dataframe.sort_values(by=["Idade"], ascending=True)
display(tabela_ordenada_idades)

   ID      Nome Departamento  Salario  Idade Data_Admissao
5   6    Felipe   Engenharia     6100     40    2017-08-12
3   4     Diego   Engenharia     6000     35    2018-02-15
7   8      Hugo   Engenharia     5800     33    2019-10-02
6   7  Gabriela   Financeiro     4700     30    2022-05-09
2   3     Carla   Financeiro     4500     26    2021-11-01
9  10      João   Financeiro     4300     27    2020-09-18
0   1       Ana   Financeiro     4200     28    2020-03-10
8   9      Iara      Compras     3900     25    2021-06-25
1   2     Bruno      Compras     3800     31    2019-07-22
4   5     Elisa      Compras     3700     29    2020-12-20

   ID      Nome Departamento  Salario  Idade Data_Admissao
8   9      Iara      Compras     3900     25    2021-06-25
2   3     Carla   Financeiro     4500     26    2021-11-01
9  10      João   Financeiro     4300     27    2020-09-18
0   1       Ana   Financeiro     4200     28    2020-03-10
4   5     Elisa      Compras     3700     29    2020-12-20
6   7  Gabriela   Financeiro     4700     30    2022-05-09
1   2     Bruno      Compras     3800     31    2019-07-22
7   8      Hugo   Engenharia     5800     33    2019-10-02
3   4     Diego   Engenharia     6000     35    2018-02-15
5   6    Felipe   Engenharia     6100     40    2017-08-12