# Curso básico de Pandas

In [2]:
import pandas as pd

## Criando um dataframe simples

In [3]:
#dataframe = pd.DataFrame()
#Criando um dataframe a partir de dicionários do python
dic_vendas = {"Data da Venda": ['15/02/2021'],
              "valor": [500],
              "Produto": ["Feijão"],
              "Quantidade": [50]
}

tabela_vendas = pd.DataFrame(dic_vendas)

In [4]:
print(tabela_vendas)
display(tabela_vendas)

  Data da Venda  valor Produto  Quantidade
0    15/02/2021    500  Feijão          50

  Data da Venda  valor Produto  Quantidade
0    15/02/2021    500  Feijão          50

## Criando dataframe a partir de base do excel

In [5]:
tabela_vendas = pd.read_excel("Vendas.xlsx") #Cria o Dataframe
display(tabela_vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [6]:
display(tabela_vendas.head(10))
display(tabela_vendas.describe())

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105

,Código Venda,Data,Quantidade,Valor Unitário,Valor Final
count,93910.000000,93910,93910.000000,93910.000000,93910.000000
mean,32464.762155,2019-06-16 23:52:28.265360896,2.166553,191.725886,414.862656
min,1.000000,2019-01-01 00:00:00,1.000000,30.000000,30.000000
25%,16204.000000,2019-03-26 00:00:00,1.000000,100.000000,156.000000
50%,32367.000000,2019-06-17 00:00:00,2.000000,155.000000,274.000000
75%,48793.750000,2019-09-08 00:00:00,3.000000,248.000000,524.000000
max,65014.000000,2019-11-30 00:00:00,5.000000,750.000000,3750.000000
std,18809.007093,NaN,1.258732,145.215519,434.846228

Uma série do Pandas é quando se tem apenas uma única coluna. Dessa maneira, o python interpreta como sendo uma "Série do Pandas" e não uma tabela.
Quando tem mais de uma coluna, se torna uma tabela

In [7]:
produtos = tabela_vendas["Produto"] #-> Exibe uma série do pandas
display(produtos)

0           Sapato Estampa
1                 Camiseta
2            Sapato Xadrez
3                  Relógio
4             Chinelo Liso
               ...
93905       Mochila Xadrez
93906    Pulseira Listrado
93907       Cueca Listrado
93908       Pulseira Linho
93909        Casaco Xadrez
Name: Produto, Length: 93910, dtype: object

In [8]:
produtos_2 = tabela_vendas[["Produto", "Data"]]
display(produtos_2)

                 Produto       Data
0         Sapato Estampa 2019-01-01
1               Camiseta 2019-01-01
2          Sapato Xadrez 2019-01-01
3                Relógio 2019-01-02
4           Chinelo Liso 2019-01-02
...                  ...        ...
93905     Mochila Xadrez 2019-11-30
93906  Pulseira Listrado 2019-11-30
93907     Cueca Listrado 2019-11-30
93908     Pulseira Linho 2019-11-30
93909      Casaco Xadrez 2019-11-30

[93910 rows x 2 columns]

O método .loc() permite pegar os dados do Dataframe a partir de alguma condição ou valor específico

In [9]:
tabela_vendas.loc[1:5] #Pegar uma linha específica 

#Pegar linhas que correspondem a uma condição. A comparação deve estar dentro dos colchetes do loc(linhas, colunas)
display(tabela_vendas.loc[tabela_vendas["ID Loja"] == "Norte Shopping", ["Data", "Produto", "Quantidade"]]) #Exibir apenas as linhas onde o ID da loja é igual à Norte Shopping

            Data                 Produto  Quantidade
3     2019-01-02                 Relógio           3
4     2019-01-02            Chinelo Liso           1
8     2019-01-02  Camisa Gola V Listrado           1
9     2019-01-02             Camisa Liso           1
100   2019-01-02            Cueca Xadrez           5
...          ...                     ...         ...
93716 2019-11-30             Polo Xadrez           1
93754 2019-11-30              Calça Liso           1
93755 2019-11-30          Casaco Estampa           2
93756 2019-11-30                   Gorro           2
93852 2019-11-30           Bermuda Linho           1

[3924 rows x 3 columns]

In [10]:
#Pegar apenas as camisetas
display(tabela_vendas.loc[tabela_vendas["Produto"] == "Camiseta", ["Código Venda", "Quantidade", "Valor Final"]])

       Código Venda  Quantidade  Valor Final
1                 1           2          360
15               11           1          180
119              93           1          180
206             148           2          360
276             199           2          360
...             ...         ...          ...
92991         64379           1          180
93050         64427           2          360
93071         64443           1          180
93577         64787           5          900
93900         65009           2          360

[783 rows x 3 columns]

In [11]:
display(tabela_vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [12]:
#Importar a base de dados de Dezembro
tabela_dezembro = pd.read_excel("Vendas - Dez.xlsx")
display(tabela_dezembro)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [18]:
#Adicionar a tabela de dezembro à tabela de vendas gerais
display(tabela_vendas)
display(tabela_dezembro)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266